AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Layout/HeredocIndentation:
  Enabled: false

Layout/LineLength:
  Max: 160

Metrics/AbcSize:
  Max: 20
  IgnoredMethods:
    - deploy!
    - validate
    - validate_position
    - validate_position_and_deploy!

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  IgnoredMethods:
    - validate
    - validate_position
  
Metrics/MethodLength:
  Max: 20
  IgnoredMethods:
    - deploy_rovers

Metrics/PerceivedComplexity:
  IgnoredMethods:
    - validate_position

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/Documentation:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - bin/*

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
